name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_xQL00NP1pwVvRHpcHSTfpmRGcEZY/L3EiNF4u5E"
